#!/usr/bin/env bash
# Usage: ./<file_name> <domain> <subdomain>
# Display information about subdomains.

# Function to retrieve and display information about the specified domain
domain_information() {
    # Perform DNS lookup for the subdomain under the specified domain
    line=$(dig "$2" "$1" | grep -A1 'ANSWER SECTION:' | tr '\t' '\n' | tail -2 | tr '\n' '')
    # Extract relevent information and display it
    echo "$2 $line" | awk '(print "The subdomain " $1 " is a " $2 " record and points to " $3)'
}

# Check the number of arguments passed to the script
if [ "$#" == 1 ]
then
    # if there is only one argument,
    # call the domain_information function with predefined subdomain names
    domain_information "$1" "www"
    domain_information "$1" "lb-01"
    domain_information "$1" "web-01"
    domain_information "$1" "web-02"
elif [ "$#" == 2 ]
then
    # if there are two arguments, call the domain_information \
    # call function with provided subdomain name
    domain_information "$1" "$2"
fi
