#!/usr/bin/env bash
# This script displays information about subdomains.

if [ $# -lt 1 ]; then
  echo "Usage: $0 <domain> [subdomain]"
  exit 1
fi

domain="$1"
subdomain="$2"

declare -A subdomains
subdomains=(
  ["www"]="A"
  ["lb-01"]="A"
  ["web-01"]="A"
  ["web-02"]="A"
)

for sub in "${!subdomains[@]}"; do
  if [ -z "$subdomain" ] || [ "$subdomain" == "$sub" ]; then
    record_type="${subdomains[$sub]}"
    dest=$(dig +short "$sub.$domain")
    if [ -n "$dest" ]; then
      echo "The subdomain $sub is a $record_type record and points to $dest"
    else
      echo "The subdomain $sub does not have a valid record"
    fi
  fi
done
