#!/usr/bin/env bash
# This script installs and configures Nginx web server

set -euo pipefail

# Update package lists
apt-get update

# Install Nginx
apt-get install -y nginx

# Configure Nginx
echo "Hello World!" | tee /var/www/html/index.html >/dev/null

# Restart Nginx without using systemctl
service nginx stop > /dev/null || true
service nginx start > /dev/null || true
