#!/usr/bin/env bash

# Configure Nginx for redirection

# Update package list
apt-get -y update

# Install Nginx
apt-get -y install nginx

# Create Nginx configuration for redirection
echo "server {
    listen 80;
    server_name _;

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }

    location / {
        echo 'Hello World!';
    }
}" | tee /etc/nginx/sites-available/redirect > /dev/null

# Create symbolic link to enable the site
ln -s /etc/nginx/sites-available/redirect /etc/nginx/sites-enabled/

# Remove default symbolic link
rm /etc/nginx/sites-enabled/default

# Reload Nginx configuration
service nginx reload

# Test redirection and show output
echo "sylvain@ubuntu$ curl -sI 127.0.0.1/redirect_me/"
curl -sI 127.0.0.1/redirect_me/
echo "sylvain@ubuntu$"
echo "Redirection test complete."

# End of script
