#!/usr/bin/env bash

# Configure Nginx for custom 404 page

# Update package list
apt-get -y update

# Install Nginx
apt-get -y install nginx

# Create Nginx configuration for custom 404 page
echo "server {
    listen 80;
    server_name _;

    error_page 404 /custom_404.html;
    location = /custom_404.html {
        internal;
        root /usr/share/nginx/html;
        echo 'Ceci n\'est pas une page';
    }

    location / {
        echo 'Hello World!';
    }
}" | tee /etc/nginx/sites-available/custom_404 > /dev/null

# Create symbolic link to enable the site
ln -s /etc/nginx/sites-available/custom_404 /etc/nginx/sites-enabled/

# Remove default symbolic link
rm /etc/nginx/sites-enabled/default

# Reload Nginx configuration
service nginx reload

# End of script

