#!/usr/bin/env bash

case "$1" in
  start)
    /tmp/manage_my_process &
    echo $! > /var/run/manage_my_process.pid
    echo "manage_my_process started"
    ;;
  stop)
    kill $(cat /var/run/manage_my_process.pid)
    rm /var/run/manage_my_process.pid
    echo "manage_my_process stopped"
    ;;
  restart)
    kill $(cat /var/run/manage_my_process.pid)
    rm /var/run/manage_my_process.pid
    /tmp/manage_my_process &
    echo $! > /var/run/manage_my_process.pid
    echo "manage_my_process restarted"
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
    ;;
esac
