#!/usr/bin/env bash
# Bash script that displays the content of the file /etc/passwd
# username, user id, Home directory path for the user

while IFS=: read -r user passwd uid gid full_name home shell; do
  # If the home directory path is not a directory, use the parent directory
  if [[ -n "$home" ]]; then
	  echo "$user:$uid:$home"
  fi
done < /etc/passwd
