#!/usr/bin/env bash

while IFS=: read -r username password uid gid full_name home_dir shell; do
    echo "The user $username is part of the $gid gang, lives in $home_dir and rides $shell. $uid's place is protected by the passcode $password, more info about the user here: $full_name"
done < /etc/passwd
