#!/usr/bin/env bash
# a Bash script that displays the time for 12 hours and 59 minutes:
# display hours from 0 to 12
# display minutes from 1 to 59
count=0
while [ $count -lt 60 ]
do
if [ $count -eq 0 ]
then
echo "Hour: 0"
else
echo "$count"
fi
(( count++ ))
done
count=0
while [ $count -le 12 ]
do
if [ $count -eq 0 ]
then
echo "Hour: 1"
else
echo "$count"
fi
((count++))
done
