#!/usr/bin/env bash
# a script that install and sets up the firewall via ufw
sudo apt update
sudo apt install ufw
sudo ufw default deny incoming
sudo ufw default allow outgoing
sudo ufw allow 22/tcp
sudo ufw allow 443/tcp
sudo ufw allow 80/tcp
sudo ufw disable
sudo ufw enable
sudo ufw status
