#!/usr/bin/env bash

# Create an RSA key pair with the specified parameters
ssh-keygen -t rsa -b 4096 -C "vagrant@ubuntu" -f school -N "betty"

# Output a message indicating the key pair has been generated
echo "Generating public/private rsa key pair."
echo "Your identification has been saved in school."
echo "Your public key has been saved in school.pub."
